[2024-05-08T14:44:31.823+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: spotify_data_pipeline.load_data_to_postgres manual__2024-05-08T14:44:02.898180+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
